#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/azure-functions/dotnet:3.0 AS base
WORKDIR /home/site/wwwroot
EXPOSE 80

FROM mcr.microsoft.com/dotnet/sdk:3.1 AS build
WORKDIR /src
COPY ["Arcus.WebApi.Health.AzureFunctions.Tests.Runtime/Arcus.WebApi.Health.AzureFunctions.Tests.Runtime.csproj", "Arcus.WebApi.Health.AzureFunctions.Tests.Runtime/"]
RUN dotnet restore "Arcus.WebApi.Health.AzureFunctions.Tests.Runtime/Arcus.WebApi.Health.AzureFunctions.Tests.Runtime.csproj"
COPY . .
WORKDIR "/src/Arcus.WebApi.Health.AzureFunctions.Tests.Runtime"
RUN dotnet build "Arcus.WebApi.Health.AzureFunctions.Tests.Runtime.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Arcus.WebApi.Health.AzureFunctions.Tests.Runtime.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /home/site/wwwroot
COPY --from=publish /app/publish .
ENV AzureWebJobsScriptRoot=/home/site/wwwroot \
    AzureFunctionsJobHost__Logging__Console__IsEnabled=true